name: Bar Assistant
version: "0.1.0"
slug: bar_assistant
description: Bar Assistant and Salt Rim packaged for Home Assistant.
url: https://docs.barassistant.app/setup/
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Salt Rim web client and reverse proxy
webui: http://[HOST]:[PORT:8099]
options:
  allow_registration: true
  api_url: /bar
  meilisearch_url: /search
  meili_master_key: ""
  use_redis: true
schema:
  allow_registration: bool
  api_url: str
  meilisearch_url: str
  meili_master_key: password?
  use_redis: bool
